"""Daily Challenge, day streak and "Practise my mistakes" (pure Python, no Streamlit).

Daily Challenge
* Five questions per day, identical for every player: generated by the normal quiz engine with a seed taken from
  the date, Mixed categories at Medium difficulty, all UN member and observer states, no recently-asked filtering.
* Heads-of-state questions are excluded (their records expire after 30 days, so a day's set could change).
* The day boundary is midnight UTC (shown in the app), so everyone shares the same day.
* Only the first completed attempt of a day counts; later attempts are practice and change nothing.

Day streak
* Consecutive days with a completed daily challenge. Completing today after yesterday adds one; a gap starts again
  at 1. The streak shown is 0 once a whole day has been missed.

Mistakes
* Facts answered wrongly or timed out are kept (deduplicated, newest last, capped). A correct answer to any question
  testing the same fact removes it. Practice rounds rebuild questions for those facts with fresh answer options.
"""
from __future__ import annotations

import random
from datetime import date, datetime, timedelta, timezone

from .data import DEFAULT_COLLECTION, get_country
from .quiz import DIFFICULTIES, generate_quiz, question_candidates

DAILY_COUNT = 5
DAILY_SETTINGS = {"continent": "World", "country_id": "all", "category": "Mixed", "difficulty": "Medium",
                  "count": DAILY_COUNT, "timer": False, "flags": True, "collection": DEFAULT_COLLECTION}
MAX_DAILY_HISTORY = 60
MAX_MISTAKES = 40


# --------------------------------------------------------------------------- daily challenge

def utc_today() -> date:
    return datetime.now(timezone.utc).date()


def seconds_until_next(now: datetime | None = None) -> int:
    now = now or datetime.now(timezone.utc)
    tomorrow = datetime.combine(now.date() + timedelta(days=1), datetime.min.time(), tzinfo=timezone.utc)
    return max(0, int((tomorrow - now).total_seconds()))


def daily_questions(day: date) -> list[dict]:
    """The day's questions. Deterministic: same date -> same questions for everyone."""
    questions, _ = generate_quiz(DAILY_SETTINGS, seed=int(day.strftime("%Y%m%d")), leaders={})
    return questions


def empty_daily() -> dict:
    return {"results": {}, "streak": 0, "best": 0, "last": ""}


def _count(v) -> bool:
    return isinstance(v, int) and not isinstance(v, bool) and v >= 0


def _iso(v) -> bool:
    try:
        return isinstance(v, str) and date.fromisoformat(v).isoformat() == v
    except ValueError:
        return False


def sanitize_daily(value) -> dict | None:
    if not isinstance(value, dict):
        return None
    out = empty_daily()
    for k in ("streak", "best"):
        if _count(value.get(k)):
            out[k] = value[k]
    if _iso(value.get("last")):
        out["last"] = value["last"]
    results = value.get("results", {})
    if isinstance(results, dict):
        clean = {d: {k: r[k] for k in ("correct", "total", "score")}
                 for d, r in results.items()
                 if _iso(d) and isinstance(r, dict) and all(_count(r.get(k)) for k in ("correct", "total", "score"))}
        out["results"] = dict(sorted(clean.items())[-MAX_DAILY_HISTORY:])
    out["best"] = max(out["best"], out["streak"])
    return out


def completed(daily: dict, day: date) -> dict | None:
    return daily["results"].get(day.isoformat())


def record_daily(daily: dict, day: date, correct: int, total: int, score: int) -> bool:
    """Record the first completed attempt of `day`. Returns False (and changes nothing) for later attempts."""
    key = day.isoformat()
    if key in daily["results"]:
        return False
    daily["results"][key] = {"correct": correct, "total": total, "score": score}
    while len(daily["results"]) > MAX_DAILY_HISTORY:
        daily["results"].pop(min(daily["results"]))
    last = date.fromisoformat(daily["last"]) if daily["last"] else None
    if last and day < last:  # an earlier day finished late (after a later one): kept, but the streak never moves back
        return True
    if last == day - timedelta(days=1):
        daily["streak"] += 1
    elif last != day:
        daily["streak"] = 1
    daily["last"] = key
    daily["best"] = max(daily["best"], daily["streak"])
    return True


def current_streak(daily: dict, today: date) -> int:
    """The streak still alive today: completed today or yesterday, otherwise 0."""
    if not daily["last"]:
        return 0
    last = date.fromisoformat(daily["last"])
    return daily["streak"] if today - last <= timedelta(days=1) else 0


def share_text(day: date, correct: int, total: int, streak: int | None, grid: str = "") -> str:
    """A result line without answers, e.g. 'World Explorer · Daily 2026-10-10 · 4/5 🟩🟩🟥🟩🟩 · 🔥 4'.
    The streak part is left out when it is None (unknown for an older day)."""
    return (f"World Explorer · Daily {day.isoformat()} · {correct}/{total}{' ' + grid if grid else ''}"
            + (f" · 🔥 {streak}" if streak is not None else ""))


def share_grid(history: list[dict]) -> str:
    return "".join("🟩" if h["correct"] else "🟥" for h in history)


# --------------------------------------------------------------------------- mistakes

def sanitize_mistakes(value) -> list[dict] | None:
    if not isinstance(value, list):
        return None
    out = []
    for m in value:
        if (isinstance(m, dict) and isinstance(m.get("facts"), list) and m["facts"]
                and all(isinstance(f, str) and len(f) < 200 for f in m["facts"])
                and isinstance(m.get("country_id"), str) and get_country(m["country_id"])
                and m.get("difficulty") in DIFFICULTIES):
            out.append({"facts": list(m["facts"]), "country_id": m["country_id"], "difficulty": m["difficulty"],
                        "kind": str(m.get("kind", ""))[:60]})
    return out[-MAX_MISTAKES:]


def note_answer(mistakes: list[dict], question: dict, correct: bool, difficulty: str) -> None:
    """Add a missed fact, or clear every stored mistake that this correct answer covers."""
    facts = set(question["facts"])
    if correct:
        mistakes[:] = [m for m in mistakes if not facts & set(m["facts"])]
        return
    mistakes[:] = [m for m in mistakes if set(m["facts"]) != facts]
    mistakes.append({"facts": list(question["facts"]), "country_id": question["country_id"],
                     "difficulty": difficulty, "kind": question.get("kind", "")})
    del mistakes[:-MAX_MISTAKES]


def practice_questions(mistakes: list[dict], leaders: dict, limit: int = 10, seed: int | None = None) -> list[dict]:
    """Fresh questions for the most recent mistakes (newest first). Facts that can no longer be asked are skipped."""
    rng = random.Random(seed)
    out, used = [], set()
    for m in reversed(mistakes):
        if len(out) >= limit:
            break
        country = get_country(m["country_id"])
        if not country or used & set(m["facts"]):
            continue
        wanted = set(m["facts"])
        found = None
        for _ in range(6):  # some questions pick a random neighbour/rival: retry until the same fact comes up
            candidates = question_candidates(country, "Mixed", m["difficulty"], rng, leaders, flags=True)
            exact = [q for q in candidates if set(q["facts"]) == wanted]
            overlap = [q for q in candidates if wanted & set(q["facts"]) and q.get("kind") == m.get("kind")]
            found = (exact or overlap or [None])[0]
            if found:
                break
        if found:
            out.append(found)
            used |= set(found["facts"])
    return out
