"""Country data, lookups and political-record validation.

Pure Python (no Streamlit) so it can be tested and reused.
data/countries.json is generated by tools/build_countries.py from mledoze/countries
(ODbL 1.0) plus the documented corrections in data/reference/. See COVERAGE.md.
"""
from __future__ import annotations

import base64
import json
from datetime import date
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
FLAG_FILE = ROOT / "assets" / "flags.json"
DEFAULT_SOURCE = "https://github.com/mledoze/countries"

CONTINENTS = ("Africa", "Asia", "Europe", "North America", "South America", "Oceania")
WORLD = "World"
AREAS = (WORLD,) + CONTINENTS
POLITICAL_MAX_AGE_DAYS = 30

STATUSES = ("un_member", "un_observer", "limited_recognition", "associated_state", "disputed_territory", "territory")
STATUS_LABELS = {
    "un_member": "UN member state",
    "un_observer": "UN observer state",
    "limited_recognition": "Limited recognition",
    "associated_state": "Associated state",
    "disputed_territory": "Disputed territory",
    "territory": "Territory or dependency",
}
# Places that may be the answer to "which country…?" questions and appear in "UN states" views.
STATE_STATUSES = frozenset({"un_member", "un_observer"})
COLLECTIONS = ("UN member and observer states", "All countries and territories")
DEFAULT_COLLECTION = COLLECTIONS[0]


def _load(name: str):
    return json.loads((DATA_DIR / name).read_text(encoding="utf-8"))


_FLAGS: dict[str, str] = json.loads(FLAG_FILE.read_text(encoding="utf-8")) if FLAG_FILE.exists() else {}


def _clean_strings(values) -> list[str]:
    return list(dict.fromkeys(v for v in (values or []) if isinstance(v, str) and v.strip()))


def normalize_country(record) -> dict | None:
    """Return a cleaned copy of a country record, or None if it is unusable.

    Only id, name and continent are required: any other missing field just
    disables the questions that need it.
    """
    if not isinstance(record, dict) or not all(isinstance(record.get(k), str) and record.get(k) for k in ("id", "name", "continent")):
        return None
    if record["continent"] not in CONTINENTS:
        return None
    c = dict(record)
    c["continents"] = [x for x in dict.fromkeys(c.get("continents") or [c["continent"]]) if x in CONTINENTS] or [c["continent"]]
    c["capitals"] = [{"name": x["name"], "role": x.get("role") or "capital"}
                     for x in c.get("capitals") or [] if isinstance(x, dict) and x.get("name")]
    c["capital_question"] = bool(c.get("capital_question", True)) and bool(c["capitals"])
    c["currencies"] = [{"code": x["code"], "name": x["name"]}
                       for x in c.get("currencies") or [] if isinstance(x, dict) and x.get("name") and x.get("code")]
    for field in ("languages", "borders", "domains", "calling_codes"):
        c[field] = _clean_strings(c.get(field))
    c["currency_question"] = bool(c.get("currency_question", True)) and bool(c["currencies"])
    c["landmarks"] = [x for x in c.get("landmarks") or [] if isinstance(x, dict) and x.get("name") and x.get("source")]
    c["region"] = c.get("region") or ""
    c["status"] = c.get("status") if c.get("status") in STATUSES else "territory"
    c["status_note"] = c.get("status_note") or ""
    c["source"] = c.get("source") or DEFAULT_SOURCE
    c["landlocked"] = bool(c.get("landlocked"))
    c["tier"] = c.get("tier") if c.get("tier") in (1, 2, 3) else 3
    c["names"] = {k: v for k, v in (c.get("names") or {}).items() if isinstance(v, str) and v}
    area = c.get("area_km2")
    c["area_km2"] = area if isinstance(area, (int, float)) and not isinstance(area, bool) and area > 0 else None
    c["flag"] = c["id"] if c["id"] in _FLAGS else None
    return c


COUNTRIES: tuple[dict, ...] = tuple(sorted(
    (c for c in map(normalize_country, _load("countries.json")) if c), key=lambda c: c["name"]))
COUNTRY_BY_ID: dict[str, dict] = {c["id"]: c for c in COUNTRIES}
STATES: tuple[dict, ...] = tuple(c for c in COUNTRIES if c["status"] in STATE_STATUSES)
PHOTOS: dict[str, dict] = {k: v for k, v in _load("photos.json").items() if k in COUNTRY_BY_ID}


def is_state(country: dict) -> bool:
    return country["status"] in STATE_STATUSES


def get_country(country_id: str | None) -> dict | None:
    return COUNTRY_BY_ID.get(country_id)


def get_countries(continent: str = WORLD, country_id: str = "all", collection: str = DEFAULT_COLLECTION) -> list[dict]:
    """Every view (Explore, Learn, settings, quiz) filters through here, so they always agree."""
    pool = STATES if collection == DEFAULT_COLLECTION else COUNTRIES
    return [c for c in pool
            if (continent == WORLD or continent in c["continents"]) and country_id in ("all", c["id"])]


def neighbours(country: dict) -> list[dict]:
    """Bordering places that exist in this collection."""
    return [n for n in map(get_country, country["borders"]) if n]


@lru_cache(maxsize=512)
def _flag_bytes(country_id: str) -> bytes:
    return base64.b64decode(_FLAGS[country_id])


def flag_image(country: dict) -> bytes | None:
    """WebP bytes of the place's flag, or None if no flag is bundled."""
    return _flag_bytes(country["flag"]) if country.get("flag") else None


def valid_political_record(record, today: date | None = None) -> bool:
    try:
        age = ((today or date.today()) - date.fromisoformat(record["verified_on"])).days
        names = record["names"]
        return (isinstance(names, list) and bool(names)
                and all(isinstance(n, str) and n.strip() for n in names)
                and bool(record.get("title"))
                and str(record.get("source", "")).startswith("https://")
                and 0 <= age <= POLITICAL_MAX_AGE_DAYS)
    except (KeyError, TypeError, ValueError):
        return False


def load_political_records(today: date | None = None, override: Path | None = None) -> dict[str, dict]:
    """Bundled records plus an optional data/heads_of_state.local.json override.

    Records older than POLITICAL_MAX_AGE_DAYS are dropped so stale leaders are never quizzed.
    """
    records = dict(_load("heads_of_state.json"))
    override = override or DATA_DIR / "heads_of_state.local.json"
    if override.exists():
        try:
            extra = json.loads(override.read_text(encoding="utf-8"))
            if isinstance(extra, dict):
                records.update({k: v for k, v in extra.items() if k in COUNTRY_BY_ID and isinstance(v, dict)})
        except (OSError, ValueError):
            pass
    return {k: v for k, v in records.items() if valid_political_record(v, today)}
