"""Write COVERAGE.md from data/countries.json and data/reference/*.json.  Usage: python tools/write_coverage_md.py"""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.data import COUNTRIES, STATUS_LABELS  # noqa: E402
from core.quiz import CODE_POOL, DOMAIN_POOL  # noqa: E402

ref = json.loads((ROOT / "data/reference/un_membership.json").read_text(encoding="utf-8"))
cur = json.loads((ROOT / "data/reference/curation.json").read_text(encoding="utf-8"))
cov = json.loads((ROOT / "data/reference/coverage.json").read_text(encoding="utf-8"))
counts = Counter(c["status"] for c in COUNTRIES)
others = sorted((c for c in COUNTRIES if c["status"] not in ("un_member",)), key=lambda c: (c["status"], c["name"]))

lines = [
    "# Country coverage", "",
    "Generated by `tools/write_coverage_md.py`. Do not edit by hand.", "",
    "## Sources", "",
    f"- Country facts: [mledoze/countries]({cov['upstream']['repository']}), commit `{cov['upstream']['commit'][:7]}` "
    f"({cov['upstream']['date']}), {cov['upstream']['entries']} entries, licence {cov['upstream']['licence']}. "
    "The adapted database in `data/` is distributed under the same licence.",
    f"- Reference list: [UN Member States]({ref['source']}) (193) and [UN non-member observer states]({ref['observer_source']}) "
    f"(2), checked {ref['checked_on']}. Stored in `data/reference/un_membership.json` with each UN name mapped to its ISO code.",
    "- Corrections and editorial decisions: `data/reference/curation.json` (each with its reason).",
    "- Facts carried over from the earlier collection: `data/reference/curated_facts.json` (sourced capital roles; UNESCO landmarks, each linked to its UNESCO page).",
    "- Flags: SVG files from the same repository, rasterised to 320 px WebP. Flags are **not** covered by the ODbL; "
    "most national flags are in the public domain, but some contain emblems with separate rights or legal restrictions "
    "(see [Wikipedia: Copyright on emblems](https://en.wikipedia.org/wiki/Wikipedia:Copyright_on_emblems)).",
    "- Heads of state: `data/heads_of_state.json`, each with source and `verified_on` date (not advanced without rechecking).", "",
    "## Reference comparison", "",
    f"- UN member states in the collection: **{counts['un_member']} of {len(ref['members'])}**",
    f"- UN observer states in the collection: **{counts['un_observer']} of {len(ref['observers'])}**",
    f"- Missing from the collection: **{', '.join(cov['missing_from_collection']) or 'none'}**",
    f"- Duplicate IDs upstream: **{', '.join(cov['duplicate_upstream_ids']) or 'none'}**; duplicate IDs in the app: **none** (tested)",
    f"- Holy See / Vatican City: {cov['holy_see_mapping']} The UN lists the *Holy See* as an observer; ISO 3166 lists "
    "*Vatican City* (VAT). They are one record, counted once, labelled “UN observer state”.",
    f"- Upstream UN-membership flags that disagree with the reference list: **{', '.join(cov['upstream_un_member_flag_disagreements']) or 'none'}** "
    "(upstream marks VAT as a UN member; the reference list takes precedence).",
    f"- Kosovo: upstream code `UNK` is stored as `XKX`.", "",
    "## Final counts", "",
    "| Status | Label shown in the app | Count |", "|---|---|---|",
]
for status, label in STATUS_LABELS.items():
    lines.append(f"| `{status}` | {label} | {counts[status]} |")
lines += [f"| | **Total places** | **{len(COUNTRIES)}** |", "",
          "By default Explore, Learn and quizzes show the 195 UN member and observer states. "
          "Choosing **All countries and territories** (settings drawer or quiz setup) adds the others, always with their status label. "
          "Only UN member and observer states are ever the answer to a “which country…?” question.", "",
          "## Excluded upstream entries", ""]
for uid, why in cur["excluded"].items():
    lines.append(f"- `{uid}` — {why}")
lines += ["", "## Places that are not UN member states", "", "| ID | Name | Status | Note |", "|---|---|---|---|"]
for c in others:
    lines.append(f"| {c['id']} | {c['name']} | {STATUS_LABELS[c['status']]} | {c['status_note']} |")
lines += ["", "## Facts that skip a question type", "",
          "Missing or disputed data removes only the affected question type; the place still appears everywhere else.", ""]
for uid, why in cur["no_capital_question"].items():
    lines.append(f"- Capital questions skipped for `{uid}`: {why}")
for uid, why in cur["no_currency_question"].items():
    lines.append(f"- Currency questions skipped for `{uid}`: {why}")
lines.append(f"- Continent questions skipped for transcontinental or differently classified places: "
             f"{', '.join(cur['continents'])}. They appear under each listed continent in filters.")
lines.append(f"- Places without currency data: {', '.join(c['id'] for c in COUNTRIES if not c['currencies']) or 'none'}.")
lines.append(f"- Places without a listed capital: {', '.join(c['id'] for c in COUNTRIES if not c['capitals']) or 'none'}.")
no_code = [c["id"] for c in COUNTRIES if not CODE_POOL[c["id"]]]
no_domain = [c["id"] for c in COUNTRIES if not DOMAIN_POOL[c["id"]]]
lines.append(f"- Calling-code questions only where one place alone uses the code ({len(COUNTRIES) - len(no_code)} places). "
             "Shared codes such as +1 (North America) and +7 (Russia and Kazakhstan) are never asked.")
lines.append(f"- Internet-domain questions only where one place alone uses the domain ({len(COUNTRIES) - len(no_domain)} places).")
lines.append(f"- UNESCO landmark questions: {sum(1 for c in COUNTRIES if c['landmarks'])} countries have single-country sites "
             "carried over from the earlier collection, each linked to its UNESCO page. Other countries have no landmark questions yet (the UNESCO data service was not reachable from the build environment).")
lines += ["", "## Corrections kept from earlier versions", "",
          "- Sri Lanka has no land border with India (upstream lists India).",
          "- Bolivia, Eswatini and Sri Lanka keep their sourced capital roles; South Africa's three capitals use roles from gov.za.",
          "- Moldova's language is recorded as Romanian.", ""]
(ROOT / "COVERAGE.md").write_text("\n".join(lines), encoding="utf-8")
print("wrote COVERAGE.md")
